/*
 - sample.h -

 Do not edit
 Generated by script

*/
#ifndef __SAMPLE_H__
#define __SAMPLE_H__
#include "sample.h"
#include "json/json.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>

class C
{
public:
	C(){};
	C(Json::Value root);
	C(const char* configFileName);
	virtual ~C();

	std::string getName() const{
		return _name;
	}

private:
	std::string _name;
};

class D
{
public:
	D(){};
	D(Json::Value root);
	D(const char* configFileName);
	virtual ~D();

	bool getA() const{
		return _a;
	}

private:
	bool _a;
};

class Sample
{
public:
	Sample(){};
	Sample(Json::Value root);
	Sample(const char* configFileName);
	virtual ~Sample();

	std::string getUsername() const{
		return _username;
	}
	std::vector<C > getC() const{
		return _c;
	}
	bool getVerified() const{
		return _verified;
	}
	D getD() const{
		return _d;
	}
	double getWeight() const{
		return _weight;
	}
	std::vector<int > getItems() const{
		return _items;
	}
	int getUserid() const{
		return _userid;
	}
	std::vector<std::string > getGames() const{
		return _games;
	}
	std::vector<std::string > getThumbnail() const{
		return _thumbnail;
	}

private:
	std::string _username;
	std::vector<C > _c;
	bool _verified;
	D _d;
	double _weight;
	std::vector<int > _items;
	int _userid;
	std::vector<std::string > _games;
	std::vector<std::string > _thumbnail;
};

#endif